version: '3.7'
services:
  postgres-provider:
    image: postgres
    container_name: postgres-provider
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"

  core-services-db:
   image: postgres
   container_name: core-services-database
   environment:
     POSTGRES_DB: core-services
     POSTGRES_USER: actitrip
     POSTGRES_PASSWORD: actitrip
   ports:
     - "5434:5432"