# APPLICATION CONFIG
spring.application.name=core-services
server.port=8090

# DATABASE CONFIGURATION (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5434/core-services
spring.datasource.username=actitrip
spring.datasource.password=actitrip
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog.xml
