# ###########################################
# APPLICATION
# ###########################################
# Application name
spring.application.name=${CORE_SERVICES_APPLICATION_NAME:core-services}

# Application port
server.port=${CORE_SERVICES_PORT_NUMBER:8090}

# ###########################################
# DATABASE CONFIGURATION
# ###########################################
spring.datasource.username=${CORE_SERVICES_DB_USERNAME:actitrip}
spring.datasource.password=${CORE_SERVICES_DB_PASSWORD:actitrip}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog.xml


